version: "3"

networks:
  app-tier:
    driver: bridge

services:

  server:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: docker/server/.Dockerfile
    command: npm run start:prod
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db

  db:
    image: library/mysql:5.7.33
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    networks:
      - app-tier
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"



