version: "3"

networks:
  app-tier:
    driver: bridge

services:

  server:
    container_name: "lucy_server"
    networks:
      - app-tier
    build:
      context: .
      dockerfile: docker/server/.Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
      - "3002:9229"
    depends_on:
      - db
      - redis

  db:
    image: library/mysql:5.7.33
    container_name: "lucy-db"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-tier
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"

  redis:
    container_name: "lucy_redis"
    image: library/redis:6.2-alpine
    ports:
      - "6380:6379"
    networks:
      - app-tier

  rabbitmq:
    container_name: "lucy-rabbit"
    image: rabb




